_dev:
    - !C.project
        name : "admin_ui"
        root : "${HOME}/devspace/admin_ui"
    - !C.version
        file : "./version.txt"
    - !C.git
        remote : "ssh://git@git.dzhcool.com:22/data/gitdata/announce"
